"""second migration

Revision ID: d47c435cdcd6
Revises: 
Create Date: 2025-01-15 05:23:21.053417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd47c435cdcd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('workSpace',
    # sa.Column('title', sa.String(length=120), nullable=False),
    # sa.Column('description', sa.Text(), nullable=False),
    # sa.Column('location', sa.String(length=120), nullable=False),
    # sa.Column('image', sa.String(length=200), nullable=True),
    # sa.Column('owner_id', sa.String(length=120), nullable=False),
    # sa.Column('id', sa.String(length=32), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('workspace')
    # with op.batch_alter_table('room', schema=None) as batch_op:
    #     batch_op.drop_constraint('room_ibfk_1', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'workSpace', ['work_space_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('is_confirmed')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('room_ibfk_1', 'workspace', ['work_space_id'], ['id'])

    op.create_table('workspace',
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owner_id', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='workspace_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('workSpace')
    # ### end Alembic commands ###
